### ISSUE TITLE
MM was already v30, you don't need to "downgrade" sepolicy version

### ISSUE THREAD

**Issue by ghost** [leskal/android_device_elephone_p9000#16]
You have kernel sources and you're using mediatek's MM-based (shitty) sepolicy. There's no need to do that :  
https://github.com/leskal/android_device_elephone_p9000/blob/ce5ad5486c27e54789bfd96967c15d570bd4c744/patches/system/sepolicy/sepolicy.patch#L4  
This is only needed on prebuilt kernels, and prebuilt kernels before O won't be able to boot O (without extensive reverts/mods)

**Comment by ghost** [comment]
If you have troubles/errors without this patch check your kernel commits (there's a list on xda "cyanogenmod for mediatek devices" thread).  
Your current sepolicy might need some changes (but I doubt it, since mediatek alps sepolicy is very open and allows almost everything).  
When CM supported wileyfox spark device, they wrote a sepolicy from scratch, mad maintained it for Nougat, and I adapted it and fixed the most painful errors. It wouldn't take much effort to use it instead :  
https://github.com/Moyster/nougat_device_meizu_m2note/tree/los-14.1/sepolicy  
I guess just file_contexts file/services/nodes and sensors policy for your sensor(s) (akmd / qmc etc.. sensors) would need to be changed. It's a much better policy **which really** enforce/prevent things.  
It's also way lighter/more confined than mtk alps sepolicy, which is better for both performance and maintenance, moving to Oreo, etc.. ;)  
You can send me a mail or a hgouts request if you need help/infos about it

**Comment by tribual** [comment]
Yeah, already read you comment @moyster and tested some weeks ago. Without patch all is running fine!

A more functional policy I really worth to think about...
